name = "nba-agent"
main = "src/index.js"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "NBAAgent", class_name = "NBAAgent" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["NBAAgent"]

[ai]
binding = "AI"
